[package]
name = "rust_image_manipulation"
version = "0.1.0"

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
lerp = "0.4.0"
num = "0.4.0"
rayon = "1.5.3"
rand = "0.8.5"